### ISSUE TITLE
Labs are passing with wrong code entries

### ISSUE THREAD

**Issue by dc79627n** [learn-co-curriculum/javascript-arrays#30] opened 2017-01-25 01:13 UTC
1) arrays "before all" hook:                                                
     Error: timeout of 2000ms exceeded. Ensure the done() callback is being ca
lled in this test.                                                            
      at Object.done (node_modules/mocha-jsdom/index.js:70:7)                 
      at process.nextTick (node_modules/jsdom/lib/jsdom.js:320:18)            
      at _combinedTickCallback (internal/process/next_tick.js:67:7)           
      at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by dc79627n** [comment] 2017-01-25 23:33
Update - I reinstalled Learn IDE and still no luck.  I am getting the same error message.

**Comment by aturkewi** [comment] 2017-02-10 22:39
@dc79627n we've had a lot of people go through this lab and have it work so I'm thinking this error may be caused by some code you've written? I think the first step is to use the Ask A Question button and get help from one of the Learn Experts. 

If there _is_ a problem with the lab, can you push your code up to github with `learn save` and  post a link to your repo of the lab. This way I can dig into the code to see what the issue may be :)

I'm going to close this for now, but please feel free to re-open if the Learn Experts also find that there is a problem with this lab :)

**Closed by aturkewi** 2017-02-10 22:39 UTC
Labels: Product

**Comment by SchruteFarms23** [comment] 2017-04-06 03:02
http://help.learn.co/workflow-tips/errors/error-timeout-of-2000ms-exceeded
